# Generated by Django 5.2.2 on 2025-06-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_post_image_alter_post_paragraph_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='paragraph',
            new_name='content_paragraph1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Autor Necunoscut', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content_paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_paragraph3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default='2025-06-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
