# Generated by Django 5.2.2 on 2025-06-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_paragraph_post_content_paragraph1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='more_details_for_the_dedicated_page',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
